//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
/// <summary>
/// Autor: Eng. Loyda Cárdenas Rey
/// </summary>

namespace WebApplicationUltimatum.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Orders = new HashSet<Order>();
            this.CustomerDemographics = new HashSet<CustomerDemographic>();
        }
        [Key]
        public string CustomerID { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string CompanyName { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string ContactName { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string ContactTitle { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string Address { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [MaxLength(15)]
        public string City { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [MaxLength(15)]
        public string Region { get; set; }
        [Required]
        [DataType(DataType.PostalCode)]
        [MaxLength(10)]
        public string PostalCode { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [MaxLength(15)]
        public string Country { get; set; }
        [Required]
        [DataType(DataType.PhoneNumber)]
        [MaxLength(24)]
        public string Phone { get; set; }
        [Required]
        [DataType(DataType.Text)]
        public string Fax { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerDemographic> CustomerDemographics { get; set; }
    }
}
